import { Button } from "@/components/ui/button";
import type { TimesheetDetailEntry } from "./types";
import { formatMinutes, signedMinutes } from "./timesheet-summary";

export function TimesheetEntryRows({ entries, canEdit, onEdit }: { entries: TimesheetDetailEntry[]; canEdit: boolean; onEdit: (entry: TimesheetDetailEntry) => void }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted/30 text-[10px] font-extrabold uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Rostered</th><th className="px-4 py-3">Attendance</th><th className="px-4 py-3">Replacement</th><th className="px-4 py-3">Actual</th><th className="px-4 py-3">Break</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3">Variance</th>{canEdit && <th className="px-4 py-3" />}</tr></thead><tbody className="divide-y divide-border">{entries.map((item) => { const entry = item.entry; return <tr key={entry._id}><td className="px-4 py-3 font-bold">{formatDate(entry.workDate)}</td><td className="px-4 py-3 font-mono text-xs">{entry.scheduledStart && entry.scheduledEnd ? `${entry.scheduledStart}–${entry.scheduledEnd}` : "Unscheduled"}</td><td className="px-4 py-3"><span className={`font-bold ${entry.attendanceType === "WORKED" ? "text-foreground" : "text-amber-700"}`}>{label(entry.attendanceType)}</span>{item.replacingEmployeeName && <p className="mt-1 text-xs text-primary">Replacing {item.replacingEmployeeName}</p>}</td><td className="px-4 py-3">{item.replacementEmployeeName ? `Replaced by ${item.replacementEmployeeName}` : "—"}</td><td className="px-4 py-3 font-mono text-xs">{entry.actualStart && entry.actualEnd ? `${entry.actualStart}–${entry.actualEnd}` : "—"}</td><td className="px-4 py-3">{entry.actualBreakMinutes !== undefined ? `${entry.actualBreakMinutes}m` : "—"}</td><td className="px-4 py-3 font-bold">{formatMinutes(entry.actualMinutes ?? 0)}</td><td className="px-4 py-3">{signedMinutes(entry.varianceMinutes ?? 0)}</td>{canEdit && <td className="px-4 py-3 text-right"><Button size="sm" variant="outline" onClick={() => onEdit(item)}>Edit</Button></td>}</tr>; })}</tbody></table></div>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("en-AU", { weekday: "short", day: "2-digit", month: "short" }).format(new Date(`${value}T00:00:00`)); }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
